class Reputation
  REPUTATION_ASK = 1
  REPUTATION_ANSWER = 1
  REPUTATION_COMMENT = 1
  REPUTATION_VOTE_UP = 15
  REPUTATION_VOTE_DOWN = 100
  REPUTATION_CREATE_TAGS = 1
  REPUTATION_EDIT_QUESTIONS_AND_ANSWERS = 2000
  
  POINTS_QUESTION_IS_VOTED_UP = 5
  POINTS_ANSWER_IS_VOTED_UP = 10
  POINTS_MARK_ANSWER_AS_ACCEPTED = 2 # Puntaje para el que marcó la mejor respuesta
  POINTS_ANSWER_IS_MARKED_AS_ACCEPTED = 15
  POINTS_QUESTION_IS_VOTED_DOWN = -2
  POINTS_ANSWER_IS_VOTED_DOWN = -2
  POINTS_VOTE_DOWN = -1
  
end